### ISSUE TITLE
Continue Training possible?

### ISSUE THREAD

**Issue by wizpig** [BMW-InnovationLab/BMW-YOLOv4-Training-Automation#13]
Hi everyone,

very nice container setup you've done there! :)

After I finished a training run, I can't seem to find a way to continue the training, i.e. to start a new training with my pre-trained weights. I could probably create a hack by modifying the container, but I wonder if there is a way how you meant it to be.

Alex

**Comment by hadikoub** [comment]
Hello,

If you mean you want to use a weights file that u have already trained to do another training as a pre-trained weights. Yes, you can do that by placing the **yolo_custom.weights** file that you obtain in the first training in the dataset folder that you want to use  and change the **train_conifg.json** model field to 

```
"model": {
        "framework": "darknet",
        "model_name": "yolov4",
	    "custom_weights": {
            "enable": true,
            "name": "yolo.weights"
        },
```
the dataset folder should look like :

```
/custom_dataset/:
                           /images
                           /labels
                           /train_config.json
                           /yolo_custom.weights
```
and then you can start the training

**Comment by wizpig** [comment]
Sorry for the late reply. Thanks alot for your answer.:)
