### ISSUE TITLE
saving tensorboard graphs at the end of the training

### ISSUE THREAD

**Issue by lidorshimoni** [BMW-InnovationLab/BMW-YOLOv4-Training-Automation#14]
hi,
 is there a way to save the mAP and loss graphs from tensorboard at the end of the training?
thanks.

**Comment by hadikoub** [comment]
![Screenshot_20201025-125816_Google.jpg](https://user-images.githubusercontent.com/31547256/97105189-ca17f900-16c1-11eb-8c27-662d8ff7a340.jpg)
Using the show data download links field a download button will apear next to every graph and then you can choose the format you want and download it.

**Comment by lidorshimoni** [comment]
thanks!
is it possible to make it save the graphs periodically / at the end of the training? or it's only possible to do it manually?

**Comment by hadikoub** [comment]
Unfortunately it is only possible to save it manually.
