### ISSUE TITLE
what images does the validate api option uses?

### ISSUE THREAD

**Issue by lidorshimoni** [BMW-InnovationLab/BMW-YOLOv4-Training-Automation#16]
is it possible to choose the image/set of images that the "validate" option in the web interface uses? or it's just randomly picked?

**Comment by hadikoub** [comment]
The images for validate are automatically choosen and therefore can be manually chosen

**Comment by lidorshimoni** [comment]
they can be manually chosen? how?

**Comment by hadikoub** [comment]
> The images for validate are automatically choosen and therefore can not be manually chosen 

No they can't be manually chosen

**Comment by lidorshimoni** [comment]
ok thanks
