### ISSUE TITLE
where does the tensorflow logs files are saved

### ISSUE THREAD

**Issue by lidorshimoni** [BMW-InnovationLab/BMW-YOLOv4-Training-Automation#17]
I want to see the tensorboard after the training has finished, so I'm trying to use:

`tensorboard --logdir path/to/logs
`
where is the "path/to/logs"?
the closest thing I saw was the "yolo_events.log" but I couldn't get this to work.

**Comment by hadikoub** [comment]
The training logs are stored inside the docker container and not exported to the host folder and therefore could not be viewed.
they are stored inside `./runs`

**Comment by lidorshimoni** [comment]
in order to use the tensorboard logs after the training has finished i change the "run_docker_linux_gpu.sh" file

```
	# start docker
	sudo docker run  --runtime=nvidia -it -e TRAIN_NAME=$container_name -e TRAIN_START_TIME="$(date '+%Y%m%d_%H:%M:%S')" $ports  -v $folder_path:/training/assets -v $(pwd)/trainings:/training/custom_training -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro --name $container_name darknet_yolov4_gpu:1 ; 

	# copy tensorboard logs
	mkdir -p tensorboard_logs/$container_name
	docker cp $container_name:/training/runs tensorboard_logs/$container_name

	
	# clean container
	sudo docker container rm $container_name
```
