### ISSUE TITLE
Enter your dataset's absolute path

### ISSUE THREAD

**Issue by longtran84** [BMW-InnovationLab/BMW-YOLOv4-Training-Automation#26]
long@long:~$ cd /home/long/Desktop/working/ai/BMW-YOLOv4-Training-Automation
long@long:~/Desktop/working/ai/BMW-YOLOv4-Training-Automation$ ./run_docker_linux_cpu.sh 
Enter your dataset's absolute path (folder containing images', labels' folders and configuration file): 
Choose a name for the docker container: 
Error: Configuration file not found in the provided path

please help me on this info, what info i need pass to here ? thanks

**Comment by hadikoub** [comment]
The path you should have as input is the  folder containing the images, labels, train_config.json as follows:
├── images
│   ├── image1.png
│   ├── image2.png
│   └──....
├── labels
│      └── yolo
│              ├── image1.txt
│              ├── image2.txt
│              └── ....
└─train_config.json

to retrieve the absolute path of the folder you can right-click your dataset folder and then go to the properties and see the parent folder, or from the command line while you navigate into your dataset folder you can retrieve the full directory using `pwd` command
