### ISSUE TITLE
AlexyAB WebUI - TensorboardX

### ISSUE THREAD

**Issue by MBelkhechine** [BMW-InnovationLab/BMW-YOLOv4-Training-Automation#32]
Hi,

is there a way to consult the graphs of the AlexeyAB WebUI and the TensorboardX after training? 

For now, there are only the files: yolo_events.log and yolo_events.log.1 which hold evaluation metrics.

Thank you in advance!

**Comment by hadikoub** [comment]
Hello, 

Unfortunately in the current version, the docker container responsible for the training is terminated at the end of the training. The training container contains both the tensorboard and the web_ui, so both are not mapped to the outside of the training container, making them unavailable at the end of the training.
